### ISSUE TITLE
Monologe

### ISSUE THREAD

**Issue by marcuswilland** [quadrama/Kleist#1]
* Längste Monologe (Väter bei FS)

**Comment by nilsreiter** [comment]
`r0vx.0` fällt total aus dem Rahmen.

**Comment by nilsreiter** [comment]
`r0vx.0` ist das Fragment und sollte wohl rausfliegen ...

**Comment by marcuswilland** [comment]
Einverstanden. Wir erinnern uns daran hierin: https://github.com/quadrama/Kleist/issues/10
