### ISSUE TITLE
Classification with kNN

### ISSUE THREAD

**Issue by nilsreiter** [quadrama/Kleist#9]
https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm

**Comment by nilsreiter** [comment]
We can reuse make_stylo_table for that purpose

**Comment by nilsreiter** [comment]
Working code in 5acb89e, accuracies using CV > 0.8 for prediction, using rel. word frequencies

**Comment by nilsreiter** [comment]
Performance drops when using only nouns, verbs and adjectives

**Comment by nilsreiter** [comment]
@marcuswilland Sowas wie ein erstes Ergebnis: 77,7% der Dramen können wir korrekt auf Basis der Worthäufigkeiten in Tragödie/Komödie einteilen. Datengrundlage sind 25 Komödien und 42 Tragödien.

**Comment by marcuswilland** [comment]
Über die techn. Grundlagen müssen wir noch reden (welches Abstandsmaß, warum 25Kom., 42Trag), das Ergebnis ist aber schon einmal sehr beeindruckend. 
Als nächstes würden wir schauen, zu welcher Zuordnung wir bei den Kleist'schen Stücken kommen und ob wir die gleiche "Schätzung" abliefern wie die Literaturwissenschaftler". D.h wir vergleichen das mit der Tabelle zu der Gattungszordnung der Kleist'schen Stücke in Literaturgeschichten
Path: \ ... \ Edinburgh\Kleist - TAGUNG FRANKFURT\Kleist_Gattungszuordnung in Literaturgeschichten)

**Comment by nilsreiter** [comment]
Was mir noch eingefallen ist: Die Majority-Baseline ( = alles ist eine Tragödie) liegt bei 62,7%, also auch gar nicht so schlecht. Das relativiert die 77 etwas. Ich probiere noch mit anderen Verfahren herum.
